spring:
  application:
    name: educationloan

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true

logging:
  config: classpath:logback-spring.xml
  file:
    name: logs/educationloan.log
    max-size: 10MB
    max-history: 30
  level:
    root: INFO
    com.example.educationloan: DEBUG
    com.example.educationloan.interceptor: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

app:
  jwt:
    secret: ${JWT_SECRET:bXlTdXBlclNlY3JldEtleVRoYXRJc0F0TGVhc3Q2NENoYXJhY3RlcnNMb25nRm9yU2VjdXJpdHk=}
    access-token-expiration-ms: 9000000
    refresh-token-expiration-ms: 604800000
  interceptor:
    #Request Logging
    request-logging:
      enabled: true
      slow-request-threshold-ms: 2000

    #Rate Limiting
    rate-limiting:
    #Token Bucket (existing)
      token-bucket:
        enabled: true
        bucket-capacity: 5
        refill-tokens: 1
        refill-duration-minutes: 1
        login-bucket-capacity: 2
        register-bucket-capacity: 3
    #Fixed Window (used by your interceptor)
#      fixed-window:
#        enabled: false
#        max-requests: 5
#        time-window-ms: 60000

    #Token Expiry
    token-expiry:
      enabled: true
      warning-before-expiry-ms: 120000
      public-urls:
        - /api/v1/auth/login
        - /api/v1/auth/register
        - /api/v1/auth/refresh

    #Audit Logging
    audit-logging:
      enabled: true
      log-anonymous: true
      exclude-urls:
        - /actuator/health
        - /actuator/info
        - /favicon.ico


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, beans
  endpoint:
    health:
      show-details: always
#http://localhost:8080/actuator/health
#http://localhost:8080/actuator/info
#http://localhost:8080/actuator/metrics
#http://localhost:8080/actuator/env

# application.properties
  spring:
      mvc:
         favicon:
               enabled: false
  logging:
    level:
       org:
       springframework:
       web:
       servlet:
        resource: WARN

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always